const $=id=>document.getElementById(id),T=GalleryTools;let state={photos:[],posts:[]},busy=false,editing=null,editingDrive=null;const pages={photos:0,slides:0};
function setBusy(value){busy=value;for(const id of ['upload','slide-upload','export-site','restore','preview','new-post','preview-home','slideshow-enabled','slide-seconds','add-remote','import-remote','all-archive','add-archive','drive-cover','save-drive','reset-drive','preview-drive'])$(id).disabled=value;}
function say(text){$('admin-message').textContent=text;}
async function commit(next){await GalleryDraft.save(next);state=next;render();}
function migrateSlides(content){return Array.isArray(content.slides)?content.slides:(content.photos||[]).filter(p=>p.slideshow!==false).map(p=>({...p,id:'s-'+p.id}));}
async function loadContent(content){const gallery=await T.loadPhotos(content.photos||[]);if(gallery.errors.length)throw Error(gallery.errors.join(' · '));let slides;if(Array.isArray(content.slides)){const result=await T.loadPhotos(content.slides);if(result.errors.length)throw Error(result.errors.join(' · '));slides=result.photos;}else slides=migrateSlides({photos:gallery.photos});return{driveAlbums:content.driveAlbums||[],photos:gallery.photos,slides,posts:[...(content.posts||[])],slideshow:normalizeSlideshow(content.slideshow),downloads:content.downloads||{allUrl:"",albums:[]}};}
async function init(){setBusy(true);try{const cached=await GalleryDraft.read();state=cached?{...cached,driveAlbums:cached.driveAlbums||[],slides:migrateSlides(cached),slideshow:normalizeSlideshow(cached.slideshow),downloads:cached.downloads||{allUrl:"",albums:[]}}:await loadContent(window.SiteContent||{});await GalleryDraft.save(state);say('Đã mở bản chỉnh sửa. Ảnh thư viện và slideshow được quản lý riêng.');render();setBusy(false);}catch(e){say(e.message+' Hãy mở bằng trình duyệt cho phép IndexedDB, hoặc chạy bằng máy chủ tĩnh.');}}
function normalizeSlideshow(s){return{enabled:s?.enabled!==false,seconds:Number.isInteger(s?.seconds)&&s.seconds>=2&&s.seconds<=30?s.seconds:3};}
function renderPhotoList(key,container){$(container).replaceChildren();const prefix=key==='photos'?'admin':'slides',total=Math.max(1,Math.ceil(state[key].length/24));pages[key]=Math.min(pages[key],total-1);$(prefix+'-page').textContent='Trang '+(pages[key]+1)+' / '+total;$(prefix+'-prev').disabled=pages[key]===0;$(prefix+'-next').disabled=pages[key]>=total-1;for(const p of state[key].slice(pages[key]*24,(pages[key]+1)*24)){const card=document.createElement('article');card.className='admin-photo';const image=document.createElement('img');image.src=p.thumbData||p.data;image.alt=p.caption||p.name;image.loading='lazy';card.append(image,T.element('small',p.name));for(const [name,title]of (key==='slides'?[['caption','Chú thích']]:[['caption','Chú thích'],['album','Album']])){const label=T.element('label',title),input=document.createElement('input');input.value=p[name]||'';input.maxLength=name==='caption'?180:80;input.onchange=async()=>{if(busy){input.value=p[name]||'';return;}setBusy(true);try{await commit({...state,[key]:state[key].map(x=>x.id===p.id?{...x,[name]:input.value.trim()}:x)});say('Đã lưu bản chỉnh sửa.');}catch(e){input.value=p[name]||'';say(e.message);}finally{setBusy(false);}};label.append(input);card.append(label);}const actions=document.createElement('div');actions.className='actions';for(const [text,fn]of [['↑',()=>move(p,-1,key)],['↓',()=>move(p,1,key)],['Xóa',()=>remove(p,key)]]){const button=T.element('button',text);button.className=text==='Xóa'?'danger':'secondary';button.setAttribute('aria-label',text==='↑'?'Đưa ảnh lên trước':text==='↓'?'Đưa ảnh xuống sau':'Xóa ảnh '+p.name);button.onclick=fn;actions.append(button);}card.append(actions);$(container).append(card);}}
function render(){renderDrive();renderArchives();const photos=state.photos;$('slideshow-enabled').checked=state.slideshow.enabled;$('slide-seconds').value=state.slideshow.seconds;$('slideshow-count').textContent=state.slides.length+' ảnh trong slideshow.';$('total').textContent=photos.length;$('size').textContent=([...photos,...state.slides].reduce((n,p)=>n+(p.size||0),0)/1024/1024).toFixed(1)+' MB';$('admin-empty').hidden=photos.length>0;$('slides-empty').hidden=state.slides.length>0;renderPhotoList('photos','admin-photos');renderPhotoList('slides','admin-slides');
$('post-list').replaceChildren();for(const p of state.posts){const row=document.createElement('article');row.className='post-row';row.append(T.element('strong',p.title),T.element('p',p.status==='published'?'Sẽ xuất bản lên trang chủ':'Bản nháp — chỉ giữ trên trình duyệt'));const edit=T.element('button','Sửa'),del=T.element('button','Xóa');edit.className='secondary';del.className='danger';edit.onclick=()=>openPost(p);del.onclick=async()=>{if(busy||!confirm('Xóa bài '+p.title+'?'))return;setBusy(true);try{await commit({...state,posts:state.posts.filter(x=>x.id!==p.id)});}catch(e){say(e.message);}finally{setBusy(false);}};row.append(edit,del);$('post-list').append(row);}}
async function move(p,direction,key){if(busy)return;const photos=[...state[key]],index=photos.findIndex(x=>x.id===p.id),target=index+direction;if(target<0||target>=photos.length)return;[photos[index],photos[target]]=[photos[target],photos[index]];setBusy(true);try{await commit({...state,[key]:photos});}catch(e){say(e.message);}finally{setBusy(false);}}
async function remove(p,key){if(busy||!confirm('Bỏ ảnh “'+p.name+'” khỏi bản chỉnh sửa?'))return;setBusy(true);try{await commit({...state,[key]:state[key].filter(x=>x.id!==p.id)});say('Đã bỏ ảnh khỏi bản chỉnh sửa. Xuất và cập nhật GitHub để thay đổi thư viện công khai.');}catch(e){say(e.message);}finally{setBusy(false);}}
function readFile(file){return new Promise((resolve,reject)=>{const r=new FileReader();r.onload=()=>resolve(r.result);r.onerror=()=>reject(Error('Không đọc được '+file.name));r.readAsDataURL(file);});}
function base64Bytes(data){const b=data.slice(data.indexOf(',')+1);return Math.floor(b.length*3/4)-(b.endsWith('==')?2:b.endsWith('=')?1:0);}
async function compressPhoto(file){const source=await readFile(file);const image=await new Promise((resolve,reject)=>{const i=new Image();i.onload=()=>resolve(i);i.onerror=()=>reject(Error('Không đọc được ảnh.'));i.src=source;});function encode(maxSide,target){let ratio=Math.min(maxSide/image.naturalWidth,maxSide/image.naturalHeight,1),quality=.82,encoded;const canvas=document.createElement('canvas');for(let attempt=0;attempt<16;attempt++){canvas.width=Math.max(1,Math.round(image.naturalWidth*ratio));canvas.height=Math.max(1,Math.round(image.naturalHeight*ratio));const c=canvas.getContext('2d');if(!c)throw Error('Trình duyệt không xử lý được ảnh.');c.fillStyle='white';c.fillRect(0,0,canvas.width,canvas.height);c.drawImage(image,0,0,canvas.width,canvas.height);encoded=canvas.toDataURL('image/webp',quality);if(!encoded.startsWith('data:image/webp;'))encoded=canvas.toDataURL('image/jpeg',quality);const bytes=Math.floor(encoded.slice(encoded.indexOf(',')+1).length*3/4);if(bytes<=target)break;if(quality>.6)quality-=.08;else ratio*=.85;}return encoded;}const data=encode(1800,240*1024),thumbData=encode(480,28*1024),type=data.slice(5,data.indexOf(';')),size=base64Bytes(data)+base64Bytes(thumbData);return{data,thumbData,type,size};}
async function validImage(data){await new Promise((resolve,reject)=>{const image=new Image();image.onload=()=>image.naturalWidth&&image.naturalHeight?resolve():reject(Error('Ảnh không hợp lệ.'));image.onerror=()=>reject(Error('Không giải mã được ảnh.'));image.src=data;});}
async function uploadImages(e,key){if(busy)return;const files=[...e.target.files];if(!files.length)return;setBusy(true);const prefix=key==='photos'?'upload':'slide-upload',progress=$(prefix+'-progress'),status=$(prefix+'-status'),album=key==='photos'?$('new-album').value.trim():'';let added=0,processed=0;const errors=[];progress.hidden=false;progress.max=files.length;progress.value=0;status.textContent='Đang xử lý '+files.length+' ảnh…';
async function convert(file){try{if(!['image/jpeg','image/png','image/webp','image/gif'].includes(file.type))throw Error('Chỉ nhận JPG, PNG, WebP và GIF.');if(!file.size)throw Error('File ảnh không có dữ liệu.');const compressed=await compressPhoto(file);return{id:(key==='slides'?'s-':'p-')+(globalThis.crypto?.randomUUID?.()||Date.now()+'-'+Math.random().toString(16).slice(2)),name:T.safeName(file.name),caption:'',album,size:compressed.size,sourceSize:file.size,type:compressed.type,thumbData:compressed.thumbData,data:compressed.data};}catch(err){errors.push(file.name+': '+err.message);return null;}finally{processed++;progress.value=processed;status.textContent='Đã xử lý '+processed+' / '+files.length+' ảnh · đã lưu '+added+' ảnh.';await new Promise(resolve=>setTimeout(resolve,0));}}
try{for(let start=0;start<files.length;start+=20){const batch=files.slice(start,start+20),results=new Array(batch.length);let next=0;async function worker(){while(next<batch.length){const index=next++;results[index]=await convert(batch[index]);}}await Promise.all([worker(),worker()]);const successful=results.filter(Boolean);if(successful.length){status.textContent='Đang lưu nhóm '+successful.length+' ảnh…';await commit({...state,[key]:[...state[key],...successful]});added+=successful.length;}}const summary='Đã thêm '+added+' / '+files.length+' ảnh. '+(errors.length?errors.slice(0,5).join(' · ')+(errors.length>5?' · Và '+(errors.length-5)+' lỗi khác.':''):'Xuất website để cập nhật GitHub.');say(summary);status.textContent=summary;}catch(err){const message='Đã lưu '+added+' ảnh. Dừng xử lý: '+err.message;say(message);status.textContent=message;}finally{e.target.value='';setBusy(false);}}
$('upload').onchange=e=>uploadImages(e,'photos');$('slide-upload').onchange=e=>uploadImages(e,'slides');
$('restore').onclick=async()=>{if(busy||!confirm('Thay toàn bộ bản chỉnh sửa bằng nội dung đã đăng kèm website này? Bản chỉnh sửa hiện tại sẽ mất.'))return;setBusy(true);try{await commit(await loadContent(window.SiteContent||{}));say('Đã khôi phục nội dung đã đăng.');}catch(e){say(e.message);}finally{setBusy(false);}};
$('preview').onclick=()=>window.open('gallery.html?preview=1','_blank','noopener');
$('export-site').onclick=async()=>{if(busy)return;setBusy(true);say('Đang đóng gói website và ảnh…');try{const localPhotos=[...new Map([...state.photos,...state.slides].filter(p=>p.data?.startsWith('data:')).map(p=>[p.id,p])).values()];const paths=new Map(localPhotos.map((p,i)=>[p.id,'photos/part-'+(i%4+1)+'/'+p.id+'.js']));function metadata({data,thumbData,_loading,...p}){return paths.has(p.id)?{...p,file:paths.get(p.id)}:p;}const content={version:5,driveAlbums:state.driveAlbums,downloads:state.downloads,slideshow:state.slideshow,slides:state.slides.map(metadata),photos:state.photos.map(metadata),posts:state.posts.filter(p=>p.status==='published')};const files=Object.entries(window.SiteFiles).map(([name,data])=>({name,data}));for(const [name,b64]of Object.entries(window.SiteBinaryFiles||{})){const raw=atob(b64),bytes=new Uint8Array(raw.length);for(let i=0;i<raw.length;i++)bytes[i]=raw.charCodeAt(i);files.push({name,data:bytes});}files.push({name:'site-package.js',data:'window.SiteFiles='+JSON.stringify(window.SiteFiles)+';window.SiteBinaryFiles='+JSON.stringify(window.SiteBinaryFiles||{})+';\n'});files.push({name:'gallery-data.js',data:'window.SiteContent='+JSON.stringify(content)+';\n'});for(const p of localPhotos)files.push({name:paths.get(p.id),data:'window.SiteGalleryImages=window.SiteGalleryImages||{};window.SiteGalleryImages['+JSON.stringify(p.id)+']='+JSON.stringify(p.data)+';window.SiteGalleryThumbs=window.SiteGalleryThumbs||{};window.SiteGalleryThumbs['+JSON.stringify(p.id)+']='+JSON.stringify(p.thumbData||p.data)+';\n'});T.download(await SimpleZip(files),'a5-k31-github-pages.zip');say('Đã xuất '+state.driveAlbums.length+' album Drive, '+state.photos.length+' ảnh thư viện, '+state.slides.length+' ảnh slideshow và '+content.posts.length+' bài. Giải nén ZIP, tải các file lên repo và commit để đăng.');}catch(e){say(e.message);}finally{setBusy(false);}};
function openPost(p){if(busy)return;editing=p?.id||null;$('post-form').reset();$('post-heading').textContent=p?'Sửa bài':'Tạo bài';if(p)for(const name of ['title','body','status'])$('post-form').elements[name].value=p[name];$('post-editor').showModal();}
$('new-post').onclick=()=>openPost();$('post-close').onclick=()=>{if(!busy)$('post-editor').close();};$('post-editor').addEventListener('cancel',e=>{if(busy)e.preventDefault();});$('post-form').onsubmit=async e=>{e.preventDefault();if(busy)return;const f=e.target.elements,title=f.title.value.trim(),body=f.body.value.trim();if(!title||!body)return;setBusy(true);try{const p={id:editing||'post-'+Date.now(),title,body,status:f.status.value};await commit({...state,posts:[...state.posts.filter(x=>x.id!==editing),p]});$('post-editor').close();say('Đã lưu bài trong bản chỉnh sửa. Xuất website để đăng lên GitHub.');}catch(err){say(err.message);}finally{setBusy(false);}};
$('preview-home').onclick=()=>window.open('index.html?preview=1','_blank','noopener');
async function saveSlideshow(){if(busy)return;const seconds=Number($('slide-seconds').value);if(!Number.isInteger(seconds)||seconds<2||seconds>30){$('slide-seconds').value=state.slideshow.seconds;say('Thời gian slideshow phải là số nguyên từ 2 đến 30 giây.');return;}const settings={enabled:$('slideshow-enabled').checked,seconds};setBusy(true);try{await commit({...state,slideshow:settings});say('Đã lưu cài đặt slideshow. Xuất website để cập nhật GitHub.');}catch(e){render();say(e.message);}finally{setBusy(false);}}
$('slide-seconds').onchange=saveSlideshow;$('slideshow-enabled').onchange=saveSlideshow;
function uid(){return 'url-'+(globalThis.crypto?.randomUUID?.()||Date.now()+'-'+Math.random().toString(16).slice(2));}
function externalPhoto(p){if(!p||typeof p!=='object')throw Error('Dữ liệu ảnh không hợp lệ.');const thumbnail=T.url(p.thumbnail),original=T.url(p.original),full=T.url(p.full||p.thumbnail);if(!thumbnail||!original||!full)throw Error('Ảnh cần URL HTTPS hợp lệ cho thumbnail, full và original.');const name=String(p.name||'Ảnh').slice(0,180);return{id:uid(),name,caption:String(p.caption||'').slice(0,180),album:String(p.album||'').slice(0,80),thumbnail,full,original,data:thumbnail,external:true,size:Number.isFinite(p.size)&&p.size>=0?p.size:0};}
function checkedDownloads(d){const allUrl=d?.allUrl?T.url(d.allUrl):'';if(d?.allUrl&&!allUrl)throw Error('URL ZIP tất cả không hợp lệ.');if(d?.albums&&!Array.isArray(d.albums))throw Error('Danh sách ZIP album không hợp lệ.');return{allUrl,albums:(d?.albums||[]).map(a=>{const url=T.url(a.url);if(!url)throw Error('URL ZIP album không hợp lệ.');return{name:String(a.name||a.album||'Album').slice(0,180),album:String(a.album||a.name||'').slice(0,80),url};})};}
$('remote-form').onsubmit=async e=>{e.preventDefault();if(busy)return;setBusy(true);try{const p=externalPhoto({name:$('remote-name').value,album:$('remote-album').value,thumbnail:$('remote-thumb').value,full:$('remote-full').value||$('remote-thumb').value,original:$('remote-original').value}),key=$('remote-target').value;await commit({...state,[key]:[...state[key],p]});e.target.reset();say('Đã thêm liên kết. Xuất website để đăng.');}catch(e){say(e.message);}finally{setBusy(false);}};
$('import-remote').onchange=async e=>{if(busy||!e.target.files.length)return;setBusy(true);try{const data=JSON.parse(await e.target.files[0].text());if(!data||(!Array.isArray(data.photos)&&!Array.isArray(data.slides)))throw Error('JSON cần có danh sách photos hoặc slides.');const photos=(data.photos||[]).map(externalPhoto),slides=(data.slides||[]).map(externalPhoto);const downloads=data.downloads?checkedDownloads(data.downloads):state.downloads;await commit({...state,photos:[...state.photos,...photos],slides:[...state.slides,...slides],downloads});say('Đã nhập '+photos.length+' ảnh thư viện và '+slides.length+' ảnh slideshow.');}catch(err){say(err.message);}finally{e.target.value='';setBusy(false);}};
function renderArchives(){$('all-archive').value=state.downloads.allUrl||'';$('admin-archives').replaceChildren();for(const [index,a]of state.downloads.albums.entries()){const row=document.createElement('div');row.className='post-row';row.append(T.element('strong',a.name));const button=T.element('button','Bỏ liên kết');button.className='danger';button.onclick=async()=>{if(busy)return;setBusy(true);try{await commit({...state,downloads:{...state.downloads,albums:state.downloads.albums.filter((_,i)=>i!==index)}});}catch(e){say(e.message);}finally{setBusy(false);}};row.append(button);$('admin-archives').append(row);}}
$('all-archive').onchange=async()=>{if(busy)return;setBusy(true);try{const downloads=checkedDownloads({...state.downloads,allUrl:$('all-archive').value.trim()});await commit({...state,downloads});say('Đã lưu liên kết tải.');}catch(e){render();say(e.message);}finally{setBusy(false);}};
$('archive-form').onsubmit=async e=>{e.preventDefault();if(busy)return;setBusy(true);try{const downloads=checkedDownloads({...state.downloads,albums:[...state.downloads.albums,{name:$('archive-name').value,album:$('archive-album').value,url:$('archive-url').value}]});await commit({...state,downloads});e.target.reset();say('Đã lưu ZIP album.');}catch(e){say(e.message);}finally{setBusy(false);}};
for(const [key,prefix]of [['photos','admin'],['slides','slides']]){ $(prefix+'-prev').onclick=()=>{if(!busy){pages[key]--;render();}};$(prefix+'-next').onclick=()=>{if(!busy){pages[key]++;render();}};}
function resetDrive(){editingDrive=null;$('drive-form').reset();$('save-drive').textContent='Thêm album';}
function renderDrive(){$('admin-drive').replaceChildren();$('drive-empty').hidden=state.driveAlbums.length>0;for(const album of state.driveAlbums){const card=document.createElement('article');card.className='admin-photo';const img=document.createElement('img');img.src=album.cover;img.alt=album.name;img.loading='lazy';card.append(img,T.element('h3',album.name));const link=T.element('a','Mở thư mục Drive ↗');link.href=T.driveUrl(album.url)||'#';link.target='_blank';link.rel='noopener';card.append(link);const actions=document.createElement('div');actions.className='actions';for(const [name,action]of [['Sửa',()=>{if(busy)return;editingDrive=album.id;$('drive-name').value=album.name;$('drive-url').value=album.url;$('drive-cover').value='';$('save-drive').textContent='Lưu album';$('drive-form').scrollIntoView?.({behavior:'smooth',block:'center'});}],['↑',()=>move(album,-1,'driveAlbums')],['↓',()=>move(album,1,'driveAlbums')],['Xóa',async()=>{if(busy||!confirm('Bỏ album “'+album.name+'” khỏi website? Ảnh trên Drive vẫn giữ.'))return;setBusy(true);try{await commit({...state,driveAlbums:state.driveAlbums.filter(a=>a.id!==album.id)});if(editingDrive===album.id)resetDrive();$('drive-message').textContent='Đã bỏ album khỏi bản chỉnh sửa.';}catch(e){$('drive-message').textContent=e.message;}finally{setBusy(false);}}]]){const b=T.element('button',name);b.className=name==='Xóa'?'danger':'secondary';b.onclick=action;actions.append(b);}card.append(actions);$('admin-drive').append(card);}}
async function coverImage(file){if(!['image/jpeg','image/png','image/webp','image/gif'].includes(file.type)||!file.size)throw Error('Chọn ảnh đại diện JPG, PNG, WebP hoặc GIF có dữ liệu.');const data=await readFile(file);const image=await new Promise((resolve,reject)=>{const i=new Image();i.onload=()=>resolve(i);i.onerror=()=>reject(Error('Không đọc được ảnh đại diện.'));i.src=data;});const ratio=Math.min(800/image.naturalWidth,800/image.naturalHeight,1);const canvas=document.createElement('canvas');canvas.width=Math.max(1,Math.round(image.naturalWidth*ratio));canvas.height=Math.max(1,Math.round(image.naturalHeight*ratio));const c=canvas.getContext('2d');if(!c)throw Error('Không xử lý được ảnh đại diện.');c.fillStyle='white';c.fillRect(0,0,canvas.width,canvas.height);c.drawImage(image,0,0,canvas.width,canvas.height);return canvas.toDataURL('image/jpeg',.82);}
$('drive-form').onsubmit=async e=>{e.preventDefault();if(busy)return;setBusy(true);$('drive-message').textContent='Đang lưu album…';try{const name=$('drive-name').value.trim(),url=T.driveUrl($('drive-url').value.trim());if(!name||!url)throw Error('Nhập tên album và link thư mục dạng https://drive.google.com/drive/folders/…');const old=state.driveAlbums.find(a=>a.id===editingDrive),file=$('drive-cover').files[0];const cover=file?await coverImage(file):old?.cover;if(!cover)throw Error('Hãy chọn ảnh đại diện cho album mới.');const album={id:editingDrive||uid(),name,url,cover};await commit({...state,driveAlbums:old?state.driveAlbums.map(a=>a.id===editingDrive?album:a):[...state.driveAlbums,album]});resetDrive();$('drive-message').textContent='Đã lưu album. Xuất website và cập nhật GitHub để đăng.';}catch(e){$('drive-message').textContent=e.message;}finally{setBusy(false);}};
$('reset-drive').onclick=()=>{if(!busy)resetDrive();};$('preview-drive').onclick=()=>window.open('gallery.html?preview=1','_blank','noopener');
init();
