const count=document.getElementById('count'),text=document.getElementById('redirect-text');let seconds=10;const timer=setInterval(()=>{seconds--;count.textContent=seconds;text.textContent='Trang web sẽ chuyển sang phần Thư viện ảnh trong vòng '+seconds+' giây nữa.';if(seconds<=0){clearInterval(timer);location.href='gallery.html';}},1000);document.getElementById('cancel').onclick=()=>{clearInterval(timer);count.textContent='✓';text.textContent='Đã dừng chuyển trang. Bạn có thể mở Thư viện ảnh bất cứ lúc nào.';document.getElementById('cancel').hidden=true;};
async function setupHome(){let content=window.SiteContent||{};if(new URLSearchParams(location.search).has('preview')){try{content=await GalleryDraft.read()||content;const note=GalleryTools.element('p','Đang xem bản chỉnh sửa trên thiết bị này — chưa đăng lên GitHub.');note.className='preview-label';document.getElementById('home-slideshow').before(note);}catch(e){document.getElementById('slide-message').textContent='Không đọc được bản xem trước: '+e.message;}}
for(const p of (content.posts||[]).filter(p=>p.status==='published')){const a=document.createElement('article');a.className='panel';const h=document.createElement('h2');h.textContent=p.title;const body=document.createElement('p');body.className='post-content';body.textContent=p.body;a.append(h,body);document.getElementById('home-posts').append(a);}
const section=document.getElementById('home-slideshow');if(content.slideshow?.enabled===false){section.hidden=true;return;}const selected=Array.isArray(content.slides)?content.slides:(content.photos||[]).filter(p=>p.slideshow!==false);if(!selected.length)return;document.getElementById('slide-message').textContent='Đang tải slideshow…';const result=await GalleryTools.loadPhotos(selected),photos=result.photos;document.getElementById('slide-message').textContent=result.errors.join(' · ');if(!photos.length)return;
const $=id=>document.getElementById(id),image=$('slide-image'),caption=$('slide-caption');let current=0,paused=false,autoplay=null;const interval=Number.isInteger(content.slideshow?.seconds)&&content.slideshow.seconds>=2&&content.slideshow.seconds<=30?content.slideshow.seconds:3;
function show(index){current=(index+photos.length)%photos.length;const p=photos[current];image.src=p.full||p.data;image.alt=p.caption||p.name;caption.textContent=p.caption||p.album||p.name;caption.hidden=false;$('slide-position').textContent=(current+1)+' / '+photos.length;for(const [i,button]of [...$('slide-dots').children].entries()){button.classList.toggle('selected',i===current);button.setAttribute('aria-pressed',String(i===current));}}
function schedule(){if(autoplay!==null)clearInterval(autoplay);autoplay=null;if(!paused&&photos.length>1&&!document.hidden)autoplay=setInterval(()=>show(current+1),interval*1000);}
for(const [i,p]of photos.entries()){const b=document.createElement('button');b.className='slide-dot';b.setAttribute('aria-label','Xem ảnh slideshow '+(i+1)+': '+(p.caption||p.name));b.onclick=()=>{show(i);schedule();};$('slide-dots').append(b);}
$('slide-prev').onclick=()=>{show(current-1);schedule();};$('slide-next').onclick=()=>{show(current+1);schedule();};$('slide-pause').onclick=()=>{paused=!paused;$('slide-pause').textContent=paused?'Tiếp tục':'Tạm dừng';$('slide-pause').setAttribute('aria-pressed',String(paused));schedule();};$('slide-pause').setAttribute('aria-pressed','false');$('slide-prev').disabled=$('slide-next').disabled=$('slide-pause').disabled=photos.length<2;document.addEventListener('visibilitychange',schedule);window.addEventListener('pagehide',()=>{if(autoplay!==null)clearInterval(autoplay);});$('slide-empty').hidden=true;image.hidden=false;$('slide-controls').hidden=false;show(0);schedule();}
if(new URLSearchParams(location.search).has('preview')){const script=document.createElement('script');script.src='draft-store.js';script.onload=setupHome;script.onerror=()=>{document.getElementById('slide-message').textContent='Không đọc được bản xem trước.';};document.head.append(script);}else setupHome();
