window.GalleryTools={
 element(tag,text){const e=document.createElement(tag);e.textContent=text;return e;},
 driveUrl(value){const safe=this.url(value);if(!safe)return null;const u=new URL(safe);return u.hostname==='drive.google.com'&&/^\/drive\/(?:u\/\d+\/)?folders\/[A-Za-z0-9_-]+\/?$/.test(u.pathname)?u.href:null;},
 url(value){try{const u=new URL(value);return u.protocol==='https:'&&!u.username&&!u.password?u.href:null;}catch(e){return null;}},
 openDownload(url,name){const safe=this.url(url);if(!safe)throw Error('Liên kết tải cần là URL HTTPS hợp lệ.');const a=document.createElement('a');a.href=safe;a.target='_blank';a.rel='noopener';a.download=name||'';document.body.append(a);a.click();a.remove();},
 safeName(name){return (name||'anh').replace(/[\\/:*?"<>|\x00-\x1f]/g,'_').slice(0,120);},
 download(blob,name){const url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=name;document.body.append(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),60000);},
 blob(data){const comma=data.indexOf(','),mime=data.slice(5,data.indexOf(';')),binary=atob(data.slice(comma+1)),bytes=new Uint8Array(binary.length);for(let i=0;i<binary.length;i++)bytes[i]=binary.charCodeAt(i);return new Blob([bytes],{type:mime});},
 async resolvePhoto(p){if(p.data)return p;if(p._loading)return p._loading;p._loading=(async()=>{window.SiteGalleryImages=window.SiteGalleryImages||{};window.SiteGalleryThumbs=window.SiteGalleryThumbs||{};if(!window.SiteGalleryImages[p.id])await new Promise((resolve,reject)=>{const script=document.createElement('script');const oldPath='photos/'+p.id+'.js',path=p.file||oldPath;if(path!==oldPath&&![1,2,3,4].some(n=>path==='photos/part-'+n+'/'+p.id+'.js')){reject(Error('Đường dẫn ảnh không hợp lệ.'));return;}script.src=path;script.onload=resolve;script.onerror=()=>reject(Error('Không đọc được '+p.name));document.head.append(script);});const data=window.SiteGalleryImages[p.id];if(typeof data!=='string'||!/^data:image\/(jpeg|png|webp|gif);base64,/.test(data))throw Error('Ảnh không hợp lệ: '+p.name);p.data=data;p.thumbData=window.SiteGalleryThumbs[p.id]||data;return p;})();try{return await p._loading;}finally{delete p._loading;}},
 async loadPhotos(photos,eager=true){const loaded=[],errors=[];for(const item of photos){try{const p={...item};if(!/^[a-zA-Z0-9_-]+$/.test(p.id))throw Error('Mã ảnh không hợp lệ.');if(p.thumbnail){const thumb=this.url(p.thumbnail),full=this.url(p.full||p.thumbnail),original=p.original?this.url(p.original):null;if(!thumb||!full||(p.original&&!original))throw Error('Liên kết ảnh không hợp lệ: '+p.name);loaded.push({...p,thumbnail:thumb,original,full,data:thumb,external:true});continue;}if(eager)await this.resolvePhoto(p);loaded.push(p);}catch(e){errors.push(e.message);}}return{photos:loaded,errors};}
};
